package main

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
)

// masks must match _masks in internal/certdata/loader.go
var masks = [4]uint64{
	0x48A5C3D2F1E6B790,
	0x2C7E91F4A836D05B,
	0xF3821C0ED7594A6E,
	0x6B4F2A8DE1097C35,
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "certgen: "+format+"\n", args...)
	os.Exit(1)
}

func readFile(path string) []byte {
	data, err := os.ReadFile(path)
	if err != nil {
		fatalf("read %s: %v", path, err)
	}
	return data
}

func encrypt(gcm cipher.AEAD, plaintext []byte) ([12]byte, []byte) {
	var nonce [12]byte
	if _, err := io.ReadFull(rand.Reader, nonce[:]); err != nil {
		fatalf("rand: %v", err)
	}
	return nonce, gcm.Seal(nil, nonce[:], plaintext, nil)
}

func fmtBytes(data []byte) string {
	var sb strings.Builder
	for i, b := range data {
		if i > 0 {
			sb.WriteString(",")
		}
		if i%16 == 0 {
			sb.WriteString("\n\t\t")
		} else {
			sb.WriteString(" ")
		}
		fmt.Fprintf(&sb, "0x%02X", b)
	}
	return sb.String()
}

func main() {
	certsDir := "certs"
	if len(os.Args) > 1 {
		certsDir = os.Args[1]
	}

	certPEM := readFile(filepath.Join(certsDir, "Certyfikat.txt"))
	interPEM := readFile(filepath.Join(certsDir, "Certyfikat posredni.txt"))
	keyPEM := readFile(filepath.Join(certsDir, "Klucz prywatny.txt"))

	// Full chain: server cert + intermediate
	chainPEM := append(certPEM, interPEM...)

	// Generate random AES-256 key
	var actualKey [32]byte
	if _, err := io.ReadFull(rand.Reader, actualKey[:]); err != nil {
		fatalf("rand: %v", err)
	}

	// XOR key parts with masks → stored values
	var kp [4]uint64
	for i := 0; i < 4; i++ {
		kp[i] = binary.LittleEndian.Uint64(actualKey[i*8:]) ^ masks[i]
	}

	block, err := aes.NewCipher(actualKey[:])
	if err != nil {
		fatalf("aes: %v", err)
	}
	gcm, err := cipher.NewGCM(block)
	if err != nil {
		fatalf("gcm: %v", err)
	}

	nonce1, encCert := encrypt(gcm, chainPEM)
	nonce2, encKey := encrypt(gcm, keyPEM)

	out := fmt.Sprintf(`package certdata

// Code generated by cmd/certgen — DO NOT EDIT.

// _kp holds key parts XOR'd with _masks from loader.go; _kp[i]^_masks[i] = actualKey[i*8:(i+1)*8]
var _kp = [4]uint64{
	0x%016X, 0x%016X,
	0x%016X, 0x%016X,
}

// _nonce1 is the AES-GCM nonce for the certificate chain.
var _nonce1 = [12]byte{%s,
}

// _nonce2 is the AES-GCM nonce for the private key.
var _nonce2 = [12]byte{%s,
}

// _encCert is the AES-256-GCM ciphertext of the certificate chain PEM.
var _encCert = []byte{%s,
}

// _encKey is the AES-256-GCM ciphertext of the private key PEM.
var _encKey = []byte{%s,
}
`,
		kp[0], kp[1], kp[2], kp[3],
		fmtBytes(nonce1[:]),
		fmtBytes(nonce2[:]),
		fmtBytes(encCert),
		fmtBytes(encKey),
	)

	outPath := filepath.Join("internal", "certdata", "encrypted.go")
	if err := os.MkdirAll(filepath.Dir(outPath), 0755); err != nil {
		fatalf("mkdir: %v", err)
	}
	if err := os.WriteFile(outPath, []byte(out), 0644); err != nil {
		fatalf("write: %v", err)
	}
	fmt.Printf("certgen: wrote %s\n", outPath)
}
